version: '3'

vars:
  DATE: '{{now | date "2006-01-02 15:04:05 MST"}}'

  LDFLAGS: -ldflags "-X 'main.Date={{.DATE}}'"

tasks:

  default: 
    cmds:    
      - task: dmptool

  dmptool:
    deps: [test]
    cmds:    
      - go build {{.LDFLAGS}} -v .

  test:
    cmds:
      - go test ./...
