# .github/workflows/release.yaml
name: Release binary
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:

    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date -u +%Y%m%d-%H%M) >> ${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and release
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        ldflags: -X "main.Date=${{ env.BUILD_TIME }}"
