# .github/workflows/release.yaml
name: Release binary
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-windows-amd64:
    name: release windows/amd64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        
